pipeline {
    agent any
    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'master', description: 'Branch name')
    }
    stages {
        stage('Build') {
            steps {
                echo 'sh "running iptables playbook"'
            }
        }
    }
}